[project]
name = "lichessapi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "berserk>=0.14.0",
    "httpx>=0.28.1",
    "mcp[cli]>=1.17.0",
]
